# Generated by Django 5.1.6 on 2025-02-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('distance', models.FloatField()),
                ('weight', models.FloatField()),
                ('calories', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Calories',
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.DeleteModel(
            name='Pulse',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='guest', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymous', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user'),
        ),
    ]
