# Generated by Django 5.1.6 on 2025-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_steps_user_alter_pulse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
