# Generated by Django 5.1.6 on 2025-02-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_pulse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
