# Generated by Django 5.1.6 on 2025-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_pulse_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calories',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='distance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distance',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='steps',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steps',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weight',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
