# Generated by Django 5.1.6 on 2025-02-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_calories_id_alter_calories_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
